/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.outros;

import com.mycompany.ferramentas.BancoDeDadosMySql;
import com.mycompany.visao.categoria.CadCategoria;
import com.mycompany.visao.categoria.ListCategoria;
import com.mycompany.visao.cidade.CadCidade;
import com.mycompany.visao.cidade.ListCidade;
import com.mycompany.visao.estado.CadEstado;
import com.mycompany.visao.estado.ListEstado;
import com.mycompany.visao.pais.CadPais;
import com.mycompany.visao.pais.ListPais;
import javax.swing.JOptionPane;

/**
 *
 * @author kaua.1880
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()){
            JOptionPane.showMessageDialog(null, "nao foi possivel se conectar ao banco de dados ");
            System.exit(0);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadrastroCategoria = new javax.swing.JMenuItem();
        miCadastroPais = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        miCadastroCidade = new javax.swing.JMenuItem();
        ListCategoria = new javax.swing.JMenu();
        miConsultaCategoria = new javax.swing.JMenuItem();
        miConsultaPais = new javax.swing.JMenuItem();
        miConsultaEstado = new javax.swing.JMenuItem();
        miConsultaCidade = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        miCadrastroCategoria.setText("Categoria");
        miCadrastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadrastroCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadrastroCategoria);

        miCadastroPais.setText("pais");
        miCadastroPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPaisActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroPais);

        jMenuItem1.setText("estado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        miCadastroCidade.setText("Cidade");
        miCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroCidade);

        jMenuBar1.add(jMenu1);

        ListCategoria.setText("Consultas");

        miConsultaCategoria.setText("Categoria");
        miConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCategoriaActionPerformed(evt);
            }
        });
        ListCategoria.add(miConsultaCategoria);

        miConsultaPais.setText("Pais");
        miConsultaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPaisActionPerformed(evt);
            }
        });
        ListCategoria.add(miConsultaPais);

        miConsultaEstado.setText("Estado");
        miConsultaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEstadoActionPerformed(evt);
            }
        });
        ListCategoria.add(miConsultaEstado);

        miConsultaCidade.setText("Cidade");
        miConsultaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCidadeActionPerformed(evt);
            }
        });
        ListCategoria.add(miConsultaCidade);

        jMenuBar1.add(ListCategoria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCategoriaActionPerformed
       ListCategoria listCategoria = new ListCategoria(); 
       listCategoria.setVisible(true);

    }//GEN-LAST:event_miConsultaCategoriaActionPerformed

    private void miCadrastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadrastroCategoriaActionPerformed
        // TODO add your handling code here:
        CadCategoria cadCategoria = new CadCategoria();
        cadCategoria.setVisible(true);        
    }//GEN-LAST:event_miCadrastroCategoriaActionPerformed

    private void miCadastroPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPaisActionPerformed
        // TODO add your handling code here:
          CadPais cadPais = new CadPais();
          cadPais.setVisible(true);
    }//GEN-LAST:event_miCadastroPaisActionPerformed

    private void miConsultaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEstadoActionPerformed
        // TODO add your handling code here:
        ListEstado listEstado = new ListEstado();
        listEstado.setVisible(true);
    }//GEN-LAST:event_miConsultaEstadoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         CadEstado cadEstado = new CadEstado();
          cadEstado.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miConsultaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPaisActionPerformed
        // TODO add your handling code here:
        ListPais listPais = new ListPais();
        listPais.setVisible(true);
                
    }//GEN-LAST:event_miConsultaPaisActionPerformed

    private void miCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCidadeActionPerformed
        // TODO add your handling code here:
        CadCidade cadCidade = new CadCidade();
        cadCidade.setVisible(true);
    }//GEN-LAST:event_miCadastroCidadeActionPerformed

    private void miConsultaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCidadeActionPerformed
        // TODO add your handling code here:
         ListCidade listCidade = new ListCidade();
        listCidade.setVisible(true);
    }//GEN-LAST:event_miConsultaCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ListCategoria;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem miCadastroCidade;
    private javax.swing.JMenuItem miCadastroPais;
    private javax.swing.JMenuItem miCadrastroCategoria;
    private javax.swing.JMenuItem miConsultaCategoria;
    private javax.swing.JMenuItem miConsultaCidade;
    private javax.swing.JMenuItem miConsultaEstado;
    private javax.swing.JMenuItem miConsultaPais;
    // End of variables declaration//GEN-END:variables
}
